// [seamvk] Native Vulkan renderer: see include/runtime/ps2_seamvk.h and seamvk/seamgs_internal.h.
// Built only with the paraLLEl-GS backend (it shares its Granite device). The GLSL lives in
// src/lib/seamvk/; the .inc files are their SPIR-V (glslc -mfmt=num), regenerated by hand.
//
// Render targets: one RGBA8 image per FRAME base (fbp), one D32 image per ZBUF base, all at a
// fixed logical 1024x512 GS pixels times PS2X_SEAMVK_SCALE. Draws run in stream order, switching
// render passes when the target pair changes. Targets hold exact GS bytes (alpha included); the
// As/128 blend factors come from a dual-source fragment output.
// At the swap the CRTC circuits (DISPFB/DISPLAY) are composed into a 640x448*scale frame,
// read back and handed to the present thread.
#include "runtime/ps2_seamvk.h"
#include "runtime/ps2_gs_pgs.h"   // [targetdump] the backend's view of a target
#include "seamvk/seamgs_internal.h"

#include "device.hpp"
#include "command_buffer.hpp"
#include "image.hpp"
#include "buffer.hpp"
#include "sampler.hpp"

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <mutex>
#include <vector>

namespace seamvk
{
    namespace
    {
        const uint32_t kSeamVert[] = {
#include "seamvk/seam.vert.inc"
        };
        const uint32_t kGsVert[] = {
#include "seamvk/gs.vert.inc"
        };
        const uint32_t kGsFrag[] = {
#include "seamvk/gs.frag.inc"
        };
        const uint32_t kGsFragNp[] = {
#include "seamvk/gs_np.frag.inc"
        };
        const uint32_t kPresentVert[] = {
#include "seamvk/present.vert.inc"
        };
        const uint32_t kPresentFrag[] = {
#include "seamvk/present.frag.inc"
        };
        const uint32_t kRtVert[] = {
#include "seamvk/rtdecode.vert.inc"
        };
        const uint32_t kRtFrag[] = {
#include "seamvk/rtdecode.frag.inc"
        };
        struct RtPC { uint32_t tex[4], clut[4], src[4], texa[4]; };

        struct PC { float view[4]; float texInfo[4]; int32_t fA[4]; int32_t fB[4]; float fogcol[4]; };
        static_assert(sizeof(PC) == 80, "push constants");
        struct PresentPC { float src[4], dst[4], alpha[4]; };

        constexpr uint32_t kLogicalW = 1024, kLogicalH = 512;
        constexpr uint32_t kOutW = 640, kOutH = 448;

        std::mutex g_mtx;
        std::vector<uint8_t> g_frame;    // newest readback, RGBA8
        uint32_t g_frameW = 0, g_frameH = 0;
        bool g_frameFresh = false;

        struct Target { Vulkan::ImageHandle img; VkImageLayout layout = VK_IMAGE_LAYOUT_UNDEFINED; bool cleared = false; };
        struct Gpu
        {
            Vulkan::Program *progSeam = nullptr, *progGs = nullptr, *progPresent = nullptr, *progRt = nullptr;
            Vulkan::ImageHandle out;            // the composed frame
            Vulkan::ImageHandle white;          // 1x1 for untextured draws
            Vulkan::ImageHandle snap;           // destination snapshot for DATE draws
            Vulkan::BufferHandle readback;
            struct Pending { Vulkan::BufferHandle buf; Vulkan::Fence fence; uint32_t w = 0, h = 0; bool live = false; };
            Pending ring[3]; uint32_t ringNext = 0;
            std::map<uint32_t, Target> targets; // by fbp
            std::map<uint32_t, Target> depths;  // by zbp
            std::map<uint32_t, uint32_t> targetPsm;   // 16 or 32: the format class a target was first drawn with
            bool dumpRt = false;                      // this frame: read decoded textures back and write them as PPM
            std::vector<std::pair<Vulkan::ImageHandle, seamgs::RtDecode>> rtDumps;
            std::vector<Vulkan::ImageHandle> tex;
            uint32_t w = 0, h = 0, scale = 1;
            bool failed = false;
            uint64_t frames = 0, draws = 0, verts = 0, passes = 0, texUploads = 0, dateDraws = 0, skippedDrawn = 0, texMissing = 0, texMismatch = 0, rtDecodes = 0, aliasedDraws = 0;
            double msTake = 0, msRecord = 0, msSubmit = 0, msWait = 0;
        };
        Gpu g_gpu;

        uint32_t scale()
        {
            static const uint32_t s = [](){ const char *v = std::getenv("PS2X_SEAMVK_SCALE"); const int n = v && v[0] ? std::atoi(v) : 2; return (uint32_t)(n < 1 ? 1 : n > 8 ? 8 : n); }();
            return s;
        }

        bool ensureGpu(Vulkan::Device &dev)
        {
            if (g_gpu.failed) return false;
            const uint32_t sc = scale(), w = kOutW * sc, h = kOutH * sc;
            if (!g_gpu.progGs)
            {
                Vulkan::ResourceLayout vl = {}, fl = {};
                vl.sets[0].uniform_buffer_mask = 1u << 0; vl.sets[0].meta[0].array_size = 1;
                vl.input_mask = 0xFu; vl.output_mask = 0xFu; vl.push_constant_size = sizeof(PC);
                fl.sets[0].sampled_image_mask = (1u << 1) | (1u << 2); fl.sets[0].meta[1].array_size = 1; fl.sets[0].meta[2].array_size = 1;
                fl.input_mask = 0xFu; fl.output_mask = 0x1u; fl.push_constant_size = sizeof(PC);
                g_gpu.progSeam = dev.request_program(kSeamVert, sizeof(kSeamVert), kGsFrag, sizeof(kGsFrag), &vl, &fl);
                Vulkan::ResourceLayout gl = {};
                gl.input_mask = 0xFu; gl.output_mask = 0xFu; gl.push_constant_size = sizeof(PC);
                g_gpu.progGs = dev.request_program(kGsVert, sizeof(kGsVert), kGsFragNp, sizeof(kGsFragNp), &gl, &fl);
                Vulkan::ResourceLayout pv = {}, pf = {};
                pv.output_mask = 0x1u; pv.push_constant_size = sizeof(PresentPC);
                pf.sets[0].sampled_image_mask = 1u << 0; pf.sets[0].meta[0].array_size = 1;
                pf.input_mask = 0x1u; pf.output_mask = 0x1u; pf.push_constant_size = sizeof(PresentPC);
                g_gpu.progPresent = dev.request_program(kPresentVert, sizeof(kPresentVert), kPresentFrag, sizeof(kPresentFrag), &pv, &pf);
                Vulkan::ResourceLayout rv = {}, rf = {};
                rv.output_mask = 0x0u; rf.output_mask = 0x1u; rf.push_constant_size = sizeof(RtPC); rv.push_constant_size = sizeof(RtPC);
                rf.sets[0].sampled_image_mask = (1u << 0) | (1u << 1); rf.sets[0].meta[0].array_size = 1; rf.sets[0].meta[1].array_size = 1;
                rf.sets[0].uniform_buffer_mask = 1u << 2; rf.sets[0].meta[2].array_size = 1;
                g_gpu.progRt = dev.request_program(kRtVert, sizeof(kRtVert), kRtFrag, sizeof(kRtFrag), &rv, &rf);
                if (!g_gpu.progSeam || !g_gpu.progGs || !g_gpu.progPresent || !g_gpu.progRt) { g_gpu.failed = true; std::fprintf(stderr, "[seamvk] shader program creation FAILED\n"); return false; }
                const uint32_t whitePx = 0xFFFFFFFFu;
                Vulkan::ImageInitialData init = { &whitePx, 0, 0 };
                g_gpu.white = dev.create_image(Vulkan::ImageCreateInfo::immutable_2d_image(1, 1, VK_FORMAT_R8G8B8A8_UNORM), &init);
            }
            if (!g_gpu.out || g_gpu.w != w || g_gpu.h != h)
            {
                auto ci = Vulkan::ImageCreateInfo::render_target(w, h, VK_FORMAT_R8G8B8A8_UNORM);
                ci.usage |= VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
                g_gpu.out = dev.create_image(ci);
                Vulkan::BufferCreateInfo bi = {};
                bi.size = VkDeviceSize(w) * h * 4u;
                bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
                bi.domain = Vulkan::BufferDomain::CachedHost;
                g_gpu.readback = dev.create_buffer(bi);
                g_gpu.w = w; g_gpu.h = h; g_gpu.scale = sc;
                std::fprintf(stderr, "[seamvk] native output %ux%u (scale %u), targets %ux%u\n", w, h, sc, kLogicalW * sc, kLogicalH * sc);
            }
            return g_gpu.out && g_gpu.readback && g_gpu.white;
        }

        uint32_t targetW(uint32_t fbw) { return std::max(1u, std::min(fbw, 16u)) * 64u; }   // logical pixels: the row width
        Target &target(Vulkan::Device &dev, uint32_t fbp, uint32_t fbw)
        {
            Target &t = g_gpu.targets[fbp];
            const uint32_t w = targetW(fbw) * g_gpu.scale;
            if (t.img && t.img->get_width() != w) { t.img.reset(); t.layout = VK_IMAGE_LAYOUT_UNDEFINED; t.cleared = false; }   // row width changed: start over
            if (!t.img)
            {
                auto ci = Vulkan::ImageCreateInfo::render_target(w, kLogicalH * g_gpu.scale, VK_FORMAT_R8G8B8A8_UNORM);
                ci.usage |= VK_IMAGE_USAGE_SAMPLED_BIT;
                t.img = dev.create_image(ci);
                t.layout = VK_IMAGE_LAYOUT_UNDEFINED; t.cleared = false;
            }
            return t;
        }
        Target &depth(Vulkan::Device &dev, uint32_t zbp, uint32_t fbw)
        {
            Target &t = g_gpu.depths[zbp | (targetW(fbw) << 16)];   // attachments of one pass share a size: one Z image per (base, width)
            if (!t.img)
            {
                auto ci = Vulkan::ImageCreateInfo::render_target(targetW(fbw) * g_gpu.scale, kLogicalH * g_gpu.scale, VK_FORMAT_D32_SFLOAT);
                ci.usage |= VK_IMAGE_USAGE_SAMPLED_BIT;
                t.img = dev.create_image(ci);
                t.layout = VK_IMAGE_LAYOUT_UNDEFINED; t.cleared = false;
            }
            return t;
        }

        void toAttachment(Vulkan::CommandBuffer &cmd, Target &t, bool isDepth)
        {
            const VkImageLayout want = isDepth ? VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL : VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
            const VkPipelineStageFlags2 st = isDepth ? (VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT) : VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT;
            const VkAccessFlags2 ac = isDepth ? (VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT | VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT) : (VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT);
            if (t.layout == VK_IMAGE_LAYOUT_UNDEFINED)
                cmd.image_barrier(*t.img, VK_IMAGE_LAYOUT_UNDEFINED, want, st, 0, st, ac);
            else if (t.layout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL || t.layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL)
                cmd.image_barrier(*t.img, t.layout, want, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT, st, ac);
            else   // attachment -> attachment: order the passes
                cmd.image_barrier(*t.img, want, want, st, ac, st, ac);
            t.layout = want;
        }
        void toSampled(Vulkan::CommandBuffer &cmd, Target &t)
        {
            if (t.layout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL) return;
            if (t.layout == VK_IMAGE_LAYOUT_UNDEFINED)
                cmd.image_barrier(*t.img, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, 0, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT);
            else
                cmd.image_barrier(*t.img, t.layout, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT,
                                  VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT);
            t.layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
        }

        void freeTextures(const seamgs::FrameList &f)
        {   // after the frame's draws: retired slots may still be referenced by them
            for (int32_t s : f.texFrees) if (s >= 0 && (size_t)s < g_gpu.tex.size()) g_gpu.tex[s].reset();
        }
        void depthToSampled(Vulkan::CommandBuffer &cmd, Target &t)
        {
            if (t.layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL) return;
            const VkPipelineStageFlags2 st = VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT;
            if (t.layout == VK_IMAGE_LAYOUT_UNDEFINED)
                cmd.image_barrier(*t.img, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, 0, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT);
            else
                cmd.image_barrier(*t.img, t.layout, VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, st, VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT);
            t.layout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL;
        }

        // kind 2: build texture slot r.slot from a render target (see rtdecode.frag)
        void runRtDecode(Vulkan::CommandBuffer &cmd, Vulkan::Device &dev, const seamgs::RtDecode &r)
        {
            auto it = g_gpu.targets.find(r.srcFbp);
            if (it == g_gpu.targets.end() || !it->second.img || r.slot < 0 || r.w == 0 || r.h == 0) return;
            Target &src = it->second;
            toSampled(cmd, src);
            Target *dz = nullptr;
            if (r.depthSrc) { auto zi = g_gpu.depths.find(r.srcFbp | ((src.img->get_width() / g_gpu.scale) << 16)); if (zi != g_gpu.depths.end() && zi->second.img) { dz = &zi->second; depthToSampled(cmd, *dz); } }
            if ((size_t)r.slot >= g_gpu.tex.size()) g_gpu.tex.resize(size_t(r.slot) + 1u);
            Vulkan::ImageHandle &img = g_gpu.tex[r.slot];
            if (!img || img->get_width() != r.w || img->get_height() != r.h)
            {
                auto ci = Vulkan::ImageCreateInfo::render_target(r.w, r.h, VK_FORMAT_R8G8B8A8_UNORM);
                ci.usage |= VK_IMAGE_USAGE_SAMPLED_BIT;
                img = dev.create_image(ci);
            }
            cmd.image_barrier(*img, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, 0, VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT);
            Vulkan::RenderPassInfo rp = {};
            rp.num_color_attachments = 1; rp.color_attachments[0] = &img->get_view(); rp.clear_attachments = 1u << 0; rp.store_attachments = 1u << 0;
            cmd.begin_render_pass(rp);
            cmd.set_opaque_state();
            cmd.set_program(g_gpu.progRt);
            cmd.set_cull_mode(VK_CULL_MODE_NONE);
            cmd.set_depth_test(false, false);
            cmd.set_primitive_topology(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
            RtPC pc = {};
            pc.tex[0] = r.tbp; pc.tex[1] = r.tbw; pc.tex[2] = r.psm; pc.tex[3] = 0;
            pc.clut[0] = r.cbp; pc.clut[1] = r.cpsm; pc.clut[2] = r.csa; pc.clut[3] = (r.clutFromTarget ? 1u : 0u) | ((r.depthSrc && dz) ? 2u : 0u);
            pc.src[0] = r.srcFbp; pc.src[1] = r.srcFbw; pc.src[2] = r.srcRows; pc.src[3] = g_gpu.scale;
            pc.texa[0] = (uint32_t)(r.texa & 0xFFu); pc.texa[1] = (uint32_t)((r.texa >> 15) & 1u); pc.texa[2] = (uint32_t)((r.texa >> 32) & 0xFFu); pc.texa[3] = 0;
            cmd.push_constants(&pc, 0, sizeof(pc));
            cmd.set_texture(0, 0, src.img->get_view(), Vulkan::StockSampler::NearestClamp);
            cmd.set_texture(0, 1, dz ? dz->img->get_view() : g_gpu.white->get_view(), Vulkan::StockSampler::NearestClamp);
            void *ub = cmd.allocate_constant_data(0, 2, sizeof(r.clut));
            std::memcpy(ub, r.clut, sizeof(r.clut));
            cmd.draw(3);
            cmd.end_render_pass();
            cmd.image_barrier(*img, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT,
                              VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT);
            ++g_gpu.rtDecodes;
            if (g_gpu.dumpRt) g_gpu.rtDumps.push_back({ img, r });
        }

        void uploadTextures(Vulkan::Device &dev, seamgs::FrameList &f)
        {
            for (seamgs::TexUpload &u : f.texUploads)
            {
                if (u.slot < 0 || u.w == 0 || u.h == 0) continue;
                if ((size_t)u.slot >= g_gpu.tex.size()) g_gpu.tex.resize(size_t(u.slot) + 1u);
                Vulkan::ImageInitialData init = { u.rgba.data(), 0, 0 };
                g_gpu.tex[u.slot] = dev.create_image(Vulkan::ImageCreateInfo::immutable_2d_image(u.w, u.h, VK_FORMAT_R8G8B8A8_UNORM), &init);
                ++g_gpu.texUploads;
            }
        }

        // Cv = (A - B) * C + D with A,B,D in {Cs, Cd, 0} and C in {As, Ad, FIX}: the Vulkan factors when expressible.
        bool blendFor(const seamgs::State &t, VkBlendFactor &sf, VkBlendFactor &df, VkBlendOp &op)
        {
            // As/128 comes from the second fragment output (dual-source); Ad/128 is approximated by Ad/255 until the
            // destination-alpha blends go through the snapshot path.
            const VkBlendFactor cf  = t.aC == 0u ? VK_BLEND_FACTOR_SRC1_ALPHA : t.aC == 1u ? VK_BLEND_FACTOR_DST_ALPHA : VK_BLEND_FACTOR_CONSTANT_ALPHA;
            const VkBlendFactor icf = t.aC == 0u ? VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA : t.aC == 1u ? VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA : VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA;
            op = VK_BLEND_OP_ADD;
            if (t.aA == 0u && t.aB == 1u && t.aD == 1u)      { sf = cf; df = icf; return true; }                                    // Cs*C + Cd*(1-C)
            if (t.aA == 0u && t.aB == 2u && t.aD == 1u)      { sf = cf; df = VK_BLEND_FACTOR_ONE; return true; }                    // Cs*C + Cd
            if (t.aA == 1u && t.aB == 0u && t.aD == 0u)      { sf = icf; df = cf; return true; }                                    // Cd*C + Cs*(1-C)
            if (t.aA == 2u && t.aB == 0u && t.aD == 1u)      { sf = cf; df = VK_BLEND_FACTOR_ONE; op = VK_BLEND_OP_REVERSE_SUBTRACT; return true; }   // Cd - Cs*C
            if (t.aA == 0u && t.aB == 2u && t.aD == 2u)      { sf = cf; df = VK_BLEND_FACTOR_ZERO; return true; }                   // Cs*C
            if (t.aA == 1u && t.aB == 2u && t.aD == 0u)      { sf = VK_BLEND_FACTOR_ONE; df = cf; return true; }                    // Cd*C + Cs
            if (t.aA == 2u && t.aB == 1u && t.aD == 0u)      { sf = VK_BLEND_FACTOR_ONE; df = cf; op = VK_BLEND_OP_SUBTRACT; return true; }   // Cs - Cd*C
            if (t.aA == t.aB)                                { sf = t.aD == 0u ? VK_BLEND_FACTOR_ONE : VK_BLEND_FACTOR_ZERO; df = t.aD == 1u ? VK_BLEND_FACTOR_ONE : VK_BLEND_FACTOR_ZERO; return true; }   // D only
            return false;
        }

        void bindDraw(Vulkan::CommandBuffer &cmd, const seamgs::Draw &d0, uint32_t sc)
        {
            static const bool s_flat = [](){ const char *v = std::getenv("PS2X_SEAMVK_FLAT"); return v && v[0] && v[0] != '0'; }();
            seamgs::Draw dFlat; const seamgs::Draw *dp = &d0;
            if (s_flat && d0.kind == 1) { dFlat = d0; dFlat.st.tme = 0; dFlat.st.abe = 0; dFlat.st.ate = 0; dp = &dFlat; }
            const seamgs::Draw &d = *dp;
            const seamgs::State &t = d.st;
            static const VkCompareOp ops[4] = { VK_COMPARE_OP_NEVER, VK_COMPARE_OP_ALWAYS, VK_COMPARE_OP_GREATER_OR_EQUAL, VK_COMPARE_OP_GREATER };
            cmd.set_depth_test(true, t.zmsk == 0u);
            cmd.set_depth_compare(t.zte ? ops[t.ztst & 3u] : VK_COMPARE_OP_ALWAYS);
            VkBlendFactor sf = VK_BLEND_FACTOR_ONE, df = VK_BLEND_FACTOR_ZERO; VkBlendOp op = VK_BLEND_OP_ADD;
            static const int s_noBlend = [](){ const char *v = std::getenv("PS2X_SEAMVK_NOBLEND"); return v && v[0] ? std::atoi(v) : 0; }();
            const bool blend = !s_noBlend && t.abe && blendFor(t, sf, df, op);
            cmd.set_blend_enable(blend);
            if (blend)
            {
                cmd.set_blend_factors(sf, VK_BLEND_FACTOR_ONE, df, VK_BLEND_FACTOR_ZERO);   // alpha channel: the source alpha is stored as is
                cmd.set_blend_op(op, VK_BLEND_OP_ADD);
                const float bc[4] = { t.fix / 128.0f, t.fix / 128.0f, t.fix / 128.0f, t.fix / 128.0f };
                cmd.set_blend_constants(bc);
            }
            uint32_t mask = 0;
            if ((t.fbmsk & 0x000000FFu) != 0x000000FFu) mask |= VK_COLOR_COMPONENT_R_BIT;
            if ((t.fbmsk & 0x0000FF00u) != 0x0000FF00u) mask |= VK_COLOR_COMPONENT_G_BIT;
            if ((t.fbmsk & 0x00FF0000u) != 0x00FF0000u) mask |= VK_COLOR_COMPONENT_B_BIT;
            if ((t.fbmsk & 0xFF000000u) != 0xFF000000u) mask |= VK_COLOR_COMPONENT_A_BIT;
            cmd.set_color_write_mask(mask);
            // Scissor in GS pixels, clipped to the target's row width (draws past it would wrap in VRAM).
            const uint32_t rowW = (t.fbw ? t.fbw : 1u) * 64u;
            uint32_t x0 = std::min<uint32_t>(t.scax0, rowW), x1 = std::min<uint32_t>(t.scax1 + 1u, rowW);
            uint32_t y0 = std::min<uint32_t>(t.scay0, kLogicalH), y1 = std::min<uint32_t>(t.scay1 + 1u, kLogicalH);
            if (x1 <= x0) x1 = std::min(x0 + 1u, rowW ? rowW : 1u);
            if (y1 <= y0) y1 = std::min(y0 + 1u, kLogicalH);
            if (x0 >= x1) x0 = x1 - 1u;
            if (y0 >= y1) y0 = y1 - 1u;
            VkRect2D sr; sr.offset.x = int32_t(x0 * sc); sr.offset.y = int32_t(y0 * sc); sr.extent.width = (x1 - x0) * sc; sr.extent.height = (y1 - y0) * sc;
            cmd.set_scissor(sr);
            PC pc = {};
            pc.view[0] = t.ofx / 16.0f; pc.view[1] = t.ofy / 16.0f; pc.view[2] = float(targetW(t.fbw)); pc.view[3] = float(kLogicalH);
            const bool tex = t.tme && t.tex >= 0 && (size_t)t.tex < g_gpu.tex.size() && g_gpu.tex[t.tex];
            if (t.tme && !tex) ++g_gpu.texMissing;
            else if (tex && (g_gpu.tex[t.tex]->get_width() != t.texW || g_gpu.tex[t.tex]->get_height() != t.texH)) ++g_gpu.texMismatch;
            pc.texInfo[0] = float(t.texW ? t.texW : 1u); pc.texInfo[1] = float(t.texH ? t.texH : 1u);
            pc.fA[0] = (tex ? 1 : 0) | (t.fst ? 2 : 0) | (t.mmag ? 8 : 0) | (t.ate ? 16 : 0) | (t.fba ? 32 : 0) | (t.tcc ? 128 : 0) | (t.fge ? 256 : 0)
                     | (t.date ? 512 : 0) | (t.datm ? 1024 : 0);
            pc.fA[1] = t.tfx; pc.fA[2] = t.wms | (t.wmt << 2); pc.fA[3] = t.atst | (t.aref << 3) | (t.afail << 11);
            pc.fB[0] = t.minu; pc.fB[1] = t.maxu; pc.fB[2] = t.minv; pc.fB[3] = t.maxv;
            pc.fogcol[0] = (t.fogcol & 0xFFu) / 255.0f; pc.fogcol[1] = ((t.fogcol >> 8) & 0xFFu) / 255.0f; pc.fogcol[2] = ((t.fogcol >> 16) & 0xFFu) / 255.0f; pc.fogcol[3] = 1.0f;
            cmd.push_constants(&pc, 0, sizeof(pc));
            cmd.set_texture(0, 1, tex ? g_gpu.tex[t.tex]->get_view() : g_gpu.white->get_view(), Vulkan::StockSampler::NearestClamp);
            cmd.set_texture(0, 2, (t.date && g_gpu.snap) ? g_gpu.snap->get_view() : g_gpu.white->get_view(), Vulkan::StockSampler::NearestClamp);
            if (t.date) ++g_gpu.dateDraws;
        }

        void composeCircuit(Vulkan::CommandBuffer &cmd, uint64_t dispfb, uint64_t display, float alpha, bool blend)
        {
            const uint32_t fbp = (uint32_t)(dispfb & 0x1FFu) * 32u, fbw = (uint32_t)((dispfb >> 9) & 0x3Fu);
            const uint32_t dbx = (uint32_t)((dispfb >> 32) & 0x7FFu), dby = (uint32_t)((dispfb >> 43) & 0x7FFu);
            const uint32_t magh = (uint32_t)((display >> 23) & 0xFu) + 1u, magv = (uint32_t)((display >> 27) & 3u) + 1u;
            const uint32_t dw = (uint32_t)((display >> 32) & 0xFFFu) + 1u, dh = (uint32_t)((display >> 44) & 0x7FFu) + 1u;
            uint32_t srcW = dw / magh, srcH = dh / magv;   // in frame pixels
            if (srcW == 0u) srcW = (fbw ? fbw : 8u) * 64u;
            if (srcH == 0u) srcH = kOutH;
            auto it = g_gpu.targets.find(fbp);
            { static int s_n = 0; if (s_n++ < 6) std::fprintf(stderr, "[seamvk] circuit (alpha %.2f blend %d): dispfb %016llx display %016llx -> fbp 0x%x fbw %u dbx %u dby %u mag %ux%u dw %u dh %u src %ux%u target %s\n",
                                                             alpha, blend ? 1 : 0, (unsigned long long)dispfb, (unsigned long long)display, fbp, fbw, dbx, dby, magh, magv, dw, dh, srcW, srcH, it == g_gpu.targets.end() ? "MISSING" : "ok"); }
            if (it == g_gpu.targets.end() || !it->second.img) return;
            PresentPC p = {};
            const float lw = float(it->second.img->get_width() / g_gpu.scale);
            p.src[0] = float(dbx) / lw; p.src[1] = float(dby) / kLogicalH; p.src[2] = float(srcW) / lw; p.src[3] = float(srcH) / kLogicalH;
            p.dst[0] = -1.0f; p.dst[1] = -1.0f; p.dst[2] = 1.0f; p.dst[3] = 1.0f;
            p.alpha[0] = alpha;
            cmd.set_blend_enable(blend);
            if (blend) { cmd.set_blend_factors(VK_BLEND_FACTOR_SRC_ALPHA, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA); cmd.set_blend_op(VK_BLEND_OP_ADD); }
            cmd.push_constants(&p, 0, sizeof(p));
            cmd.set_texture(0, 0, it->second.img->get_view(), Vulkan::StockSampler::LinearClamp);
            cmd.draw(4);
        }
    }

    bool on()
    {
        static const bool s = [](){ const char *v = std::getenv("PS2X_SEAMVK"); return v && v[0] && v[0] != '0'; }();
        return s;
    }

    bool takeFrame(std::vector<uint8_t> &rgba, uint32_t &w, uint32_t &h)
    {
        std::lock_guard<std::mutex> lk(g_mtx);
        if (!g_frameFresh) return false;
        rgba.swap(g_frame); g_frame.clear();
        w = g_frameW; h = g_frameH; g_frameFresh = false;
        return true;
    }

    void renderFrame(Vulkan::Device &dev, const PrivRegs &priv)
    {
        const auto tA = std::chrono::steady_clock::now();
        seamgs::FrameList f;
        seamgs::takeFrame(f);
        if (!ensureGpu(dev)) return;
        const auto tB = std::chrono::steady_clock::now();
        const uint32_t sc = g_gpu.scale;
        uploadTextures(dev, f);

        static const uint64_t s_dumpFrame = [](){ const char *v = std::getenv("PS2X_SEAMVK_DUMPFRAME"); return v && v[0] ? (uint64_t)std::atoll(v) : 0ull; }();
        static bool s_dumped = false;
        auto busyFight = [&]() { size_t host = 0; for (const seamgs::Draw &d : f.draws) if (d.kind == 1) ++host; return host > 200u; };
        if (s_dumpFrame && !s_dumped && ((s_dumpFrame != 1u && g_gpu.frames == s_dumpFrame) || (s_dumpFrame == 1u && busyFight())))
        {
            if (const char *dir = std::getenv("PS2X_SEAMVK_TEXDUMP"))
            {   // the backend's view of the targets this frame decodes from, for comparison with rt_*.ppm
                g_gpu.dumpRt = true;
                for (const seamgs::RtDecode &r : f.rtDecodes) { ps2x_pgs::TargetDumpReq q; q.fbp = r.srcFbp; q.fbw = r.srcFbw; q.w = r.srcFbw * 64u; q.h = r.srcRows * 32u; q.dir = dir; ps2x_pgs::requestTargetDump(q); }
            }   // PS2X_SEAMVK_DUMPFRAME=<n>: what the front-end produced for that frame (=1: the first frame with > 200 seam meshes, i.e. a fight)
            s_dumped = true;
            if (const char *dir = std::getenv("PS2X_SEAMVK_TEXDUMP"))
                for (const seamgs::TexUpload &u : f.texUploads)
                {   // what the GPU gets for each slot uploaded this frame
                    char path[512]; std::snprintf(path, sizeof(path), "%s/gpu_slot%03d_%ux%u.ppm", dir, u.slot, u.w, u.h);
                    if (FILE *fp = std::fopen(path, "wb")) { std::fprintf(fp, "P6\n%u %u\n255\n", u.w, u.h); for (size_t i = 0; i < size_t(u.w) * u.h; ++i) std::fwrite(u.rgba.data() + i * 4u, 1, 3, fp); std::fclose(fp); }
                }
            std::fprintf(stderr, "[seamvk] frame %llu: %zu draws, %zu vertex bytes, %zu tex uploads\n", (unsigned long long)g_gpu.frames, f.draws.size(), f.verts.size(), f.texUploads.size());
            for (const seamgs::FrameList::RegEvent &e : f.regEvents)
                std::fprintf(stderr, "[seamvk]  reg before draw %u path %u%s %s %016llx\n", e.drawIndex, e.path, e.hostGif ? " (host)" : "",
                             e.addr == 0x40 ? "SCISSOR_1" : e.addr == 0x41 ? "SCISSOR_2" : e.addr == 0x4c ? "FRAME_1" : "FRAME_2", (unsigned long long)e.value);
            for (size_t i = 0; i < f.draws.size(); ++i)
            {
                const seamgs::Draw &d = f.draws[i]; const seamgs::State &t = d.st;
                if (d.kind == 1)
                {   // the seam's mesh: state, and the projection the vertex shader will compute (w sign, GS z range)
                    const seamvk::Consts &c = d.c; const uint32_t n = d.count;
                    uint32_t neg = 0, pos = 0; float wmin = 1e30f, wmax = -1e30f, zqmin = 1e30f, zqmax = -1e30f;
                    for (uint32_t v = 0; v < n; ++v)
                    {
                        const float *P = reinterpret_cast<const float *>(f.verts.data() + d.vertOff + size_t(v) * d.stride);
                        float scr[4];
                        if (d.prog <= 1)
                        {
                            const float pw = d.prog == 0 ? P[3] : 1.0f;
                            for (int k = 0; k < 4; ++k) scr[k] = c.A[0][k] * P[0] + c.A[1][k] * P[1] + c.A[2][k] * P[2] + c.A[3][k] * pw;
                        }
                        else
                        {
                            float pa[3], pb[3], sk[3];
                            for (int k = 0; k < 3; ++k)
                            {
                                const float x = P[0] - c.pivA[0], y = P[1] - c.pivA[1], z = P[2] - c.pivA[2];
                                pa[k] = c.A[0][k] * x + c.A[1][k] * y + c.A[2][k] * z + c.A[3][k];
                                const float x2 = P[0] - c.pivB[0], y2 = P[1] - c.pivB[1], z2 = P[2] - c.pivB[2];
                                pb[k] = c.B[0][k] * x2 + c.B[1][k] * y2 + c.B[2][k] * z2 + c.B[3][k];
                            }
                            for (int k = 0; k < 3; ++k) sk[k] = pb[k] + (pa[k] - pb[k]) * P[3];
                            for (int k = 0; k < 4; ++k) scr[k] = c.E[0][k] * sk[0] + c.E[1][k] * sk[1] + c.E[2][k] * sk[2] + c.E[3][k];
                        }
                        const float w = -scr[3];
                        if (w < 0.0f) ++neg; else ++pos;
                        wmin = std::min(wmin, w); wmax = std::max(wmax, w);
                        if (w != 0.0f) { const float zq = scr[2] / scr[3]; zqmin = std::min(zqmin, zq); zqmax = std::max(zqmax, zq); }
                    }
                    std::fprintf(stderr, "[seamvk]  draw %zu HOST prog %u count %u w[%g..%g] neg %u pos %u zq[%g..%g] fbp 0x%x fbw %u psm %u msk %08x zbp 0x%x zte %u ztst %u zmsk %u tme %u tex %d%s abe %u (%u,%u,%u,%u) ate %u atst %u aref %u afail %u ctxt %u sc %u..%u %u..%u tex0 %08x%08x fst %u tfx %u tcc %u wms %u wmt %u %ux%u prim %03llx prmode %03llx cont %u sc1 %016llx sc2 %016llx\n",
                                 i, d.prog, n, wmin, wmax, neg, pos, zqmin, zqmax, t.fbp, t.fbw, t.fpsm, t.fbmsk, t.zbp, t.zte, t.ztst, t.zmsk, t.tme, t.tex, t.texFromDrawn ? "(DRAWN)" : "", t.abe, t.aA, t.aB, t.aC, t.aD, t.ate, t.atst, t.aref, t.afail, t.ctxt, t.scax0, t.scax1, t.scay0, t.scay1, t.tex0hi, t.tex0lo, t.fst, t.tfx, t.tcc, t.wms, t.wmt, t.texW, t.texH, (unsigned long long)t.dbgPrim, (unsigned long long)t.dbgPrmode, t.dbgPrmodecont, (unsigned long long)t.dbgSc[0], (unsigned long long)t.dbgSc[1]);
                    continue;
                }
                if (d.kind == 2 && d.rt >= 0 && (size_t)d.rt < f.rtDecodes.size())
                {
                    const seamgs::RtDecode &r = f.rtDecodes[d.rt];
                    std::fprintf(stderr, "[seamvk]  draw %zu RTDECODE slot %d %ux%u tbp 0x%x tbw %u psm %u cbp 0x%x src fbp 0x%x fbw %u rows %u depthSrc %u clutFromTarget %u\n",
                                 i, r.slot, r.w, r.h, r.tbp, r.tbw, r.psm, r.cbp, r.srcFbp, r.srcFbw, r.srcRows, r.depthSrc, r.clutFromTarget);
                    continue;
                }
                if (d.kind != 0) continue;   // list the GS draws
                std::fprintf(stderr, "[seamvk]  draw %zu kind %u prog %u count %u fbp 0x%x fbw %u psm %u msk %08x zbp 0x%x zte %u ztst %u zmsk %u tme %u fst %u tex %d%s %ux%u tex0 %08x%08x tfx %u tcc %u wms %u wmt %u abe %u (%u,%u,%u,%u) fix %u ate %u atst %u aref %u afail %u date %u sc %u..%u %u..%u\n",
                             i, d.kind, d.prog, d.count, t.fbp, t.fbw, t.fpsm, t.fbmsk, t.zbp, t.zte, t.ztst, t.zmsk, t.tme, t.fst, t.tex, t.texFromDrawn ? "(DRAWN)" : "", t.texW, t.texH, t.tex0hi, t.tex0lo, t.tfx, t.tcc, t.wms, t.wmt, t.abe, t.aA, t.aB, t.aC, t.aD, t.fix, t.ate, t.atst, t.aref, t.afail, t.date, t.scax0, t.scax1, t.scay0, t.scay1);
                if (d.kind == 0)
                    for (uint32_t v = 0; v < d.count && v < 6; ++v)
                    {
                        seamgs::Vtx x; std::memcpy(&x, f.verts.data() + d.vertOff + size_t(v) * sizeof(x), sizeof(x));
                        std::fprintf(stderr, "[seamvk]    v%u xy %.1f %.1f z %.5f q %.3f st %.3f %.3f uv %.1f %.1f rgba %08x\n", v, x.x, x.y, x.z, x.q, x.s, x.t, x.u, x.v, x.rgba);
                    }
            }
        }
        if (!g_gpu.dumpRt) g_gpu.dumpRt = s_dumpFrame && !s_dumped && std::getenv("PS2X_SEAMVK_TEXDUMP") && (s_dumpFrame != 1u && g_gpu.frames + 1u == s_dumpFrame);
        g_gpu.rtDumps.clear();
        auto cmd = dev.request_command_buffer();
        // ---- the ordered draws, into their FRAME / ZBUF targets ----
        uint32_t curFbp = ~0u, curZbp = ~0u; bool inPass = false;
        // Draws that sample pages the game rendered into (the post chain: Z as an index texture, rendered
        // palettes, frame re-views) can only read a stale mirror; they are skipped until those passes are
        // native. PS2X_SEAMVK_FEEDBACK=1 draws them anyway (diagnostics).
        static const bool s_noDate = [](){ const char *v = std::getenv("PS2X_SEAMVK_NODATE"); return v && v[0] && v[0] != '0'; }();
        static const bool s_feedback = [](){ const char *v = std::getenv("PS2X_SEAMVK_FEEDBACK"); return v && v[0] && v[0] != '0'; }();
        for (const seamgs::Draw &d : f.draws)
        {
            const seamgs::State &t = d.st;
            if (d.kind == 2)
            {
                if (inPass) { cmd->end_render_pass(); inPass = false; }
                if (d.rt >= 0 && (size_t)d.rt < f.rtDecodes.size()) runRtDecode(*cmd, dev, f.rtDecodes[d.rt]);
                curFbp = ~0u;
                continue;
            }
            if (t.texFromDrawn && !s_feedback) { ++g_gpu.skippedDrawn; continue; }
            {   // a draw through a different pixel format than the target's own (the depth-mask pass writes 2 bits per
                // 16-bit half of each 32-bit frame pixel) cannot be a plain draw into the RGBA8 target: needs its own pass
                auto &fmt = g_gpu.targetPsm[t.fbp];
                const uint32_t cls = (t.fpsm == 2u || t.fpsm == 10u) ? 16u : 32u;
                if (fmt == 0u) fmt = cls;
                else if (fmt != cls) { ++g_gpu.aliasedDraws; continue; }
            }
            {   // PS2X_SEAMVK_ONLYTEX0=<hex>: render only the GS draws whose TEX0 matches (diagnostic)
                static const uint64_t s_only = [](){ const char *v = std::getenv("PS2X_SEAMVK_ONLYTEX0"); return v && v[0] ? std::strtoull(v, nullptr, 16) : 0ull; }();
                if (s_only && d.kind == 0 && (((uint64_t)t.tex0hi << 32) | t.tex0lo) != s_only) continue;
            }
            const uint32_t zbp = (t.zte ? t.zbp : ~1u) ^ (t.fbw << 24);   // the pass key also changes with the row width
            if (t.date && !s_noDate)
            {   // DATE reads the destination: snapshot the target between passes (the scissor would do; whole image for now)
                if (inPass) { cmd->end_render_pass(); inPass = false; }
                Target &ct = target(dev, t.fbp, t.fbw);
                toAttachment(*cmd, ct, false);   // a target never drawn yet still needs a defined layout for the copy
                if (g_gpu.snap && g_gpu.snap->get_width() != ct.img->get_width()) g_gpu.snap.reset();
                if (!g_gpu.snap)
                {
                    auto ci = Vulkan::ImageCreateInfo::render_target(ct.img->get_width(), kLogicalH * g_gpu.scale, VK_FORMAT_R8G8B8A8_UNORM);
                    ci.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT; ci.initial_layout = VK_IMAGE_LAYOUT_UNDEFINED;
                    g_gpu.snap = dev.create_image(ci);
                }
                cmd->image_barrier(*ct.img, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                                   VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT, VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_READ_BIT);
                cmd->image_barrier(*g_gpu.snap, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                                   VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, 0, VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_WRITE_BIT);
                {   // only the scissor region (the HUD's DATE draws are small)
                    const uint32_t sc2 = g_gpu.scale, rowW = (t.fbw ? t.fbw : 1u) * 64u;
                    uint32_t x0 = std::min<uint32_t>(t.scax0, rowW), x1 = std::min<uint32_t>(t.scax1 + 1u, rowW), y0 = std::min<uint32_t>(t.scay0, kLogicalH), y1 = std::min<uint32_t>(t.scay1 + 1u, kLogicalH);
                    if (x1 > x0 && y1 > y0)
                    {
                        VkOffset3D off = { int32_t(x0 * sc2), int32_t(y0 * sc2), 0 };
                        VkExtent3D ext = { (x1 - x0) * sc2, (y1 - y0) * sc2, 1 };
                        cmd->copy_image(*g_gpu.snap, *ct.img, off, off, ext, { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 }, { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 });
                    }
                }
                cmd->image_barrier(*g_gpu.snap, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                                   VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT);
                cmd->image_barrier(*ct.img, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                                   VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT);
                curFbp = ~0u;   // re-open the pass below (load)
            }
            if (t.fbp != curFbp || zbp != curZbp)
            {
                if (inPass) { cmd->end_render_pass(); inPass = false; }
                Target &ct = target(dev, t.fbp, t.fbw);
                toAttachment(*cmd, ct, false);
                Vulkan::RenderPassInfo rp = {};
                rp.num_color_attachments = 1;
                rp.color_attachments[0] = &ct.img->get_view();
                rp.store_attachments = 1u << 0;
                if (!ct.cleared) { rp.clear_attachments = 1u << 0; ct.cleared = true; }
                else rp.load_attachments = 1u << 0;
                Target &dt = depth(dev, t.zte ? t.zbp : 0u, t.fbw);   // an unused Z buffer still needs an attachment: pair every pass with one
                toAttachment(*cmd, dt, true);
                rp.depth_stencil = &dt.img->get_view();
                rp.op_flags = Vulkan::RENDER_PASS_OP_STORE_DEPTH_STENCIL_BIT | (dt.cleared ? Vulkan::RENDER_PASS_OP_LOAD_DEPTH_STENCIL_BIT : Vulkan::RENDER_PASS_OP_CLEAR_DEPTH_STENCIL_BIT);
                dt.cleared = true;
                rp.clear_depth_stencil.depth = 0.0f;
                cmd->begin_render_pass(rp);
                cmd->set_opaque_state();   // Granite's fresh state has a zero colour write mask
                cmd->set_cull_mode(VK_CULL_MODE_NONE);
                inPass = true; ++g_gpu.passes;
                curFbp = t.fbp; curZbp = zbp;
            }
            bindDraw(*cmd, d, sc);
            if (d.kind == 0)
            {
                cmd->set_program(g_gpu.progGs);
                cmd->set_primitive_topology(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
                cmd->set_vertex_attrib(0, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 0);
                cmd->set_vertex_attrib(1, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 16);
                cmd->set_vertex_attrib(2, 0, VK_FORMAT_R8G8B8A8_UNORM, 32);
                cmd->set_vertex_attrib(3, 0, VK_FORMAT_R32_SFLOAT, 36);
                const size_t bytes = size_t(d.count) * sizeof(seamgs::Vtx);
                void *vb = cmd->allocate_vertex_data(0, bytes, sizeof(seamgs::Vtx));
                std::memcpy(vb, f.verts.data() + d.vertOff, bytes);
                cmd->draw(d.count);
            }
            else
            {
                cmd->set_program(g_gpu.progSeam);
                cmd->set_primitive_topology(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP);
                cmd->set_vertex_attrib(0, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 0);
                cmd->set_vertex_attrib(1, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 16);
                cmd->set_vertex_attrib(2, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 32);
                cmd->set_vertex_attrib(3, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 48);
                Consts *c = static_cast<Consts *>(cmd->allocate_constant_data(0, 0, sizeof(Consts)));
                std::memcpy(c, &d.c, sizeof(Consts));
                c->misc[1] = float(d.hostPass);
                static const bool s_flat = [](){ const char *v = std::getenv("PS2X_SEAMVK_FLAT"); return v && v[0] && v[0] != '0'; }();
                if (s_flat) c->misc[3] = 1.0f;   // PS2X_SEAMVK_FLAT=1: the seam's meshes in a flat colour per program (coverage diagnostics)
                void *vb = cmd->allocate_vertex_data(0, VkDeviceSize(64) * d.count, 64);
                uint8_t *dst = static_cast<uint8_t *>(vb);
                const uint8_t *src = f.verts.data() + d.vertOff;
                for (uint32_t v = 0; v < d.count; ++v) { std::memcpy(dst + v * 64u, src + size_t(v) * d.stride, d.stride); if (d.stride < 64u) std::memset(dst + v * 64u + d.stride, 0, 64u - d.stride); }
                cmd->draw(d.count);
            }
            ++g_gpu.draws; g_gpu.verts += d.count;
        }
        if (inPass) cmd->end_render_pass();

        // ---- compose the CRTC circuits into the output frame ----
        const uint32_t en1 = (uint32_t)(priv.pmode & 1u), en2 = (uint32_t)((priv.pmode >> 1) & 1u);
        const uint32_t mmod = (uint32_t)((priv.pmode >> 5) & 1u), alp = (uint32_t)((priv.pmode >> 8) & 0xFFu);
        for (auto &kv : g_gpu.targets) if (kv.second.img && kv.second.layout != VK_IMAGE_LAYOUT_UNDEFINED) toSampled(*cmd, kv.second);
        cmd->image_barrier(*g_gpu.out, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                           VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, 0, VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT);
        {
            Vulkan::RenderPassInfo rp = {};
            rp.num_color_attachments = 1;
            rp.color_attachments[0] = &g_gpu.out->get_view();
            rp.clear_attachments = 1u << 0; rp.store_attachments = 1u << 0;
            rp.clear_color[0].float32[0] = ((priv.bgcolor) & 0xFFu) / 255.0f; rp.clear_color[0].float32[1] = ((priv.bgcolor >> 8) & 0xFFu) / 255.0f;
            rp.clear_color[0].float32[2] = ((priv.bgcolor >> 16) & 0xFFu) / 255.0f; rp.clear_color[0].float32[3] = 1.0f;
            cmd->begin_render_pass(rp);
            cmd->set_opaque_state();
            cmd->set_program(g_gpu.progPresent);
            cmd->set_cull_mode(VK_CULL_MODE_NONE);
            cmd->set_depth_test(false, false);
            cmd->set_primitive_topology(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP);
            const bool sameBuf = en1 && en2 && (priv.dispfb1 & 0x7FFFu) == (priv.dispfb2 & 0x7FFFu);   // both circuits on one frame: one opaque blit
            if (en2 && !sameBuf) composeCircuit(*cmd, priv.dispfb2, priv.display2, 1.0f, false);
            if (en1) composeCircuit(*cmd, priv.dispfb1, priv.display1, (en2 && !sameBuf) ? (mmod ? alp / 255.0f : 0.5f) : 1.0f, en2 && !sameBuf);
            cmd->end_render_pass();
        }
        cmd->image_barrier(*g_gpu.out, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                           VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT,
                           VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_READ_BIT);
        const uint32_t w = g_gpu.w, h = g_gpu.h;
        // Asynchronous readback: this frame goes into ring slot N; the frame handed to the presenter is the oldest
        // slot whose fence has already signalled (normally the previous frame), so the swap never waits on the GPU.
        Gpu::Pending &slot = g_gpu.ring[g_gpu.ringNext % 3u];
        if (!slot.buf || slot.w != w || slot.h != h)
        {
            Vulkan::BufferCreateInfo bi = {}; bi.size = VkDeviceSize(w) * h * 4u; bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT; bi.domain = Vulkan::BufferDomain::CachedHost;
            slot.buf = dev.create_buffer(bi); slot.w = w; slot.h = h;
        }
        cmd->copy_image_to_buffer(*slot.buf, *g_gpu.out, 0, {}, { w, h, 1 }, 0, 0, { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 });
        cmd->barrier(VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_2_HOST_BIT, VK_ACCESS_2_HOST_READ_BIT);
        const auto tC = std::chrono::steady_clock::now();
        dev.submit(cmd, &slot.fence);
        slot.live = true;
        const auto tD = std::chrono::steady_clock::now();
        ++g_gpu.ringNext;
        Gpu::Pending &prev = g_gpu.ring[(g_gpu.ringNext + 1u) % 3u];   // two frames back: certainly done, no wait in practice
        Vulkan::Fence fence; bool havePrev = false;
        if (prev.live) { prev.fence->wait(); havePrev = true; }
        const auto tE = std::chrono::steady_clock::now();
        g_gpu.msTake += std::chrono::duration<double, std::milli>(tB - tA).count();
        g_gpu.msRecord += std::chrono::duration<double, std::milli>(tC - tB).count();
        g_gpu.msSubmit += std::chrono::duration<double, std::milli>(tD - tC).count();
        g_gpu.msWait += std::chrono::duration<double, std::milli>(tE - tD).count();

        if (havePrev)
        {
            const uint8_t *src = static_cast<const uint8_t *>(dev.map_host_buffer(*prev.buf, Vulkan::MEMORY_ACCESS_READ_BIT));
            {
                std::lock_guard<std::mutex> lk(g_mtx);
                g_frame.assign(src, src + size_t(prev.w) * prev.h * 4u);
                g_frameW = prev.w; g_frameH = prev.h; g_frameFresh = true;
            }
            dev.unmap_host_buffer(*prev.buf, Vulkan::MEMORY_ACCESS_READ_BIT);
            prev.live = false;
        }
        if (!g_gpu.rtDumps.empty())
        {   // PS2X_SEAMVK_TEXDUMP + DUMPFRAME: the render-target decodes of this frame as rt_*.ppm (synchronous readback)
            const char *dir = std::getenv("PS2X_SEAMVK_TEXDUMP");
            int n = 0;
            for (auto &rd : g_gpu.rtDumps)
            {
                const seamgs::RtDecode &r = rd.second;
                Vulkan::BufferCreateInfo bi = {}; bi.size = VkDeviceSize(r.w) * r.h * 4u; bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT; bi.domain = Vulkan::BufferDomain::CachedHost;
                auto buf = dev.create_buffer(bi);
                auto c2 = dev.request_command_buffer();
                c2->image_barrier(*rd.first, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, 0, VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_READ_BIT);
                c2->copy_image_to_buffer(*buf, *rd.first, 0, {}, { r.w, r.h, 1 }, 0, 0, { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 });
                c2->barrier(VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_2_HOST_BIT, VK_ACCESS_2_HOST_READ_BIT);
                c2->image_barrier(*rd.first, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_ACCESS_2_SHADER_SAMPLED_READ_BIT);
                Vulkan::Fence fe; dev.submit(c2, &fe); fe->wait();
                const uint8_t *px = static_cast<const uint8_t *>(dev.map_host_buffer(*buf, Vulkan::MEMORY_ACCESS_READ_BIT));
                char path[512];
                std::snprintf(path, sizeof(path), "%s/rt%02d_slot%d_psm%u_%ux%u_tbp%x_tbw%u_cbp%x_src%x_fbw%u_rows%u_z%u_c%u.ppm", dir, n, r.slot, r.psm, r.w, r.h, r.tbp, r.tbw, r.cbp, r.srcFbp, r.srcFbw, r.srcRows, r.depthSrc, r.clutFromTarget);
                if (FILE *fp = std::fopen(path, "wb")) { std::fprintf(fp, "P6\n%u %u\n255\n", r.w, r.h); for (size_t i = 0; i < size_t(r.w) * r.h; ++i) std::fwrite(px + i * 4u, 1, 3, fp); std::fclose(fp); }
                std::snprintf(path + std::strlen(path) - 4, 5, ".pgm");
                if (FILE *fp = std::fopen(path, "wb")) { std::fprintf(fp, "P5\n%u %u\n255\n", r.w, r.h); for (size_t i = 0; i < size_t(r.w) * r.h; ++i) std::fputc(px[i * 4u + 3u], fp); std::fclose(fp); }
                dev.unmap_host_buffer(*buf, Vulkan::MEMORY_ACCESS_READ_BIT);
                ++n;
            }
            g_gpu.rtDumps.clear();
        }
        freeTextures(f);

        if ((++g_gpu.frames % 300u) == 0u)
        {
            std::fprintf(stderr, "[seamvk] %llu frames: %.0f draws, %.0f verts, %.1f passes, %.1f tex uploads, %.1f DATE draws, %.1f feedback draws skipped, %.1f tex missing, %.1f tex size mismatch, %.1f rt decodes, %.1f aliased-format draws skipped per frame; %zu targets %zu depths\n",
                         (unsigned long long)g_gpu.frames, double(g_gpu.draws) / 300.0, double(g_gpu.verts) / 300.0, double(g_gpu.passes) / 300.0,
                         double(g_gpu.texUploads) / 300.0, double(g_gpu.dateDraws) / 300.0, double(g_gpu.skippedDrawn) / 300.0, double(g_gpu.texMissing) / 300.0, double(g_gpu.texMismatch) / 300.0, double(g_gpu.rtDecodes) / 300.0, double(g_gpu.aliasedDraws) / 300.0, g_gpu.targets.size(), g_gpu.depths.size());
            g_gpu.draws = g_gpu.verts = g_gpu.passes = g_gpu.texUploads = g_gpu.dateDraws = g_gpu.skippedDrawn = g_gpu.texMissing = g_gpu.texMismatch = g_gpu.rtDecodes = g_gpu.aliasedDraws = 0;
            std::fprintf(stderr, "[seamvk] per frame: take %.2f ms, record %.2f ms, submit %.2f ms, wait %.2f ms\n", g_gpu.msTake / 300.0, g_gpu.msRecord / 300.0, g_gpu.msSubmit / 300.0, g_gpu.msWait / 300.0);
            g_gpu.msTake = g_gpu.msRecord = g_gpu.msSubmit = g_gpu.msWait = 0;
        }
    }
}
